name: nana_mobile_task
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.4.1
  get_it: ^7.6.7
  google_fonts: ^6.2.1
  file_picker: ^6.2.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  pretty_dio_logger: ^1.3.1
  font_awesome_flutter: ^10.7.0
  mockito: ^5.4.4

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
