// Mocks generated by Mockito 5.4.4 from annotations
// in nana_mobile_task/test/products/product_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'product_data_source_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MockRemoteRequestManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockRemoteRequestManager extends _i1.Mock
    implements _i2.MockRemoteRequestManager {
  MockMockRemoteRequestManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> post({
    required String? url,
    dynamic data,
    dynamic query,
    String? token,
    _i4.ProgressCallback? progressCallback,
    _i4.CancelToken? cancelToken,
    bool? isMultipart = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [],
          {
            #url: url,
            #data: data,
            #query: query,
            #token: token,
            #progressCallback: progressCallback,
            #cancelToken: cancelToken,
            #isMultipart: isMultipart,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> get({
    required String? url,
    dynamic data,
    dynamic query,
    String? token,
    _i4.CancelToken? cancelToken,
    bool? isMultipart = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #url: url,
            #data: data,
            #query: query,
            #token: token,
            #cancelToken: cancelToken,
            #isMultipart: isMultipart,
          },
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
